Winded/RagdollMover

README.md
lua/autorun/ragdollmover.lua
lua/autorun/ragdollmover_meta.lua
lua/entities/rgm_axis/cl_init.lua
lua/entities/rgm_axis/init.lua
lua/entities/rgm_axis/shared.lua
lua/entities/rgm_axis_arrow/init.lua
lua/entities/rgm_axis_disc/init.lua
lua/entities/rgm_axis_part/shared.lua
lua/entities/rgm_axis_side/init.lua
lua/weapons/gmod_tool/stools/ragdollmover.lua
lua/weapons/gmod_tool/stools/ragmover_ikchains.lua

Added bone selection menu + mode by Le Hot Doge
"Manual bone picking" mode can select and manipulate non physical bones.
Added possibility to select bones on effect props
Added angle being displayed when rotating stuff
By default ragdoll mover can select dynamic props, ragdolls, and effects, but the filter can be turned off in case if there would be a need to grab some entity not in the filter.
Added an option to manipulate physics bone without moving/rotating its children bones.
Fixed the issue with gizmos not appearing when you just start using the tool
Fixed an error with selecting specific models that had physmeshes parented to non physical bones as "root bone", thus breaking the tool.

Ragdoll mover update

---

lua/autorun/client/ragdollmover_client.lua
lua/autorun/ragdollmover_meta.lua
lua/weapons/gmod_tool/stools/ragdollmover.lua
resource/localization/en/ragdollmover_tools.properties

New features:
- Added button to scale selected bone to 0
- Added "Precise Nonphysics Manipulation" tab that allows to manipulate nonphysical bone properties through sliders
Bugfixes:
- Fixed issue with not being able to switch gizmo modes
- Fixed issue with server not sending english language resource file to clients that don't have ragdoll mover installed
- Fixed lua error that was popping up when trying to reset selected bone to root (through reloading) when no entity was selected
- Bone manipulation is now done serverside, so info with your changes like resetting bone position and rotation will be sent to other clients

Precise Manipulation

---

lua/autorun/ragdollmover.lua

64 bit branch was too good at maths, so it was getting very small negative number in calculations where there was supposed to be no negative numbers (extracting root of a number)

Fixed issue with IK rigs on 64 bit branch of GMod

---

lua/weapons/gmod_tool/stools/ragdollmover.lua

Ragdoll mover now would be able to detect and select parented/bonemerged entities from other tools like multi parent or composite bone tool rather than just easy bonemerge and prop_effect's

Adjusted filter for picking up parented/bonemerged entities

---

lua/autorun/ragdollmover.lua
lua/entities/rgm_axis/init.lua
lua/entities/rgm_axis_arrow/init.lua
lua/entities/rgm_axis_disc/init.lua
lua/entities/rgm_axis_scale_arrow/init.lua
lua/entities/rgm_axis_scale_side/init.lua
lua/entities/rgm_axis_side/init.lua
lua/weapons/gmod_tool/stools/ragdollmover.lua
resource/localization/en/ragdollmover_tools.properties

- Cleaned up the script a bit
- Fixed issue with nonphysical bones rotating to 180 degrees when selecting them from the bonetree
- Bone manipulation sliders will now get updated when letting go of the gizmos
- Now pressing R or using ragdollmover_resetroot console command will switch between the root bone of an entity and the last selected bone. This still will consider nonphysical bones with ID 0 as "root", though, but ragdolls like that are rare, I think.
- Removed buttons for manipulating bones and moved them into bone tree right click menus
- "Reset position and angles" is now separated into resetting position and resetting rotation buttons
- Nonphysical bone manipulations now also got variants that apply their function to all children of a bone, for example like scaling whole arm of …

Small enhancements

---

lua/autorun/ragdollmover.lua
lua/autorun/ragdollmover_meta.lua
lua/entities/rgm_axis/cl_init.lua
lua/entities/rgm_axis/init.lua
lua/entities/rgm_axis/shared.lua
lua/entities/rgm_axis_arrow/cl_init.lua
lua/entities/rgm_axis_arrow/init.lua
lua/entities/rgm_axis_arrow/shared.lua
lua/entities/rgm_axis_disc/cl_init.lua
lua/entities/rgm_axis_disc/init.lua
lua/entities/rgm_axis_disc_large/cl_init.lua
lua/entities/rgm_axis_part/cl_init.lua
lua/entities/rgm_axis_scale_arrow/init.lua
lua/entities/rgm_axis_scale_side/init.lua
lua/entities/rgm_axis_side/cl_init.lua
lua/entities/rgm_axis_side/init.lua
lua/entities/rgm_axis_side_omni/cl_init.lua
lua/entities/rgm_axis_side_omni/init.lua
lua/entities/rgm_axis_side_omni/shared.lua
lua/weapons/gmod_tool/stools/ragdollmover.lua
lua/weapons/gmod_tool/stools/ragmover_ikchains.lua
resource/localization/en/ragdollmover_tools.properties

- Made GetPhysBoneParent function look through 256 possible bones rather than 128, as it seems like SFM models can get in gmod fine and their bone cap is 256 or so (nonphysical, and this function here looks through all nonphysical bones to find one which is connected to physical's parent one)
- Added functionality to lock bones to each other: To do so, right click on a physical bone in the bone tree, select "Lock to this bone" and then left click on any other physical bone to make it locked to the bone you've right clicked on. This will make locked bone move with its "parent", which by default would be only noticeable with IKs, if you lock hand to hand or to a foot. For other usage I'd suggest using ragdoll stretch. Bones can't be locked to any of the parent bones, and they also can't …

Movement upgrade

---

lua/autorun/ragdollmover.lua
lua/autorun/ragdollmover_meta.lua
lua/entities/rgm_axis/init.lua
lua/entities/rgm_axis_arrow/init.lua
lua/entities/rgm_axis_disc/init.lua
lua/entities/rgm_axis_scale_side/init.lua
lua/entities/rgm_axis_side/init.lua
lua/entities/rgm_axis_side_omni/init.lua
lua/weapons/gmod_tool/stools/ragdollmover.lua
lua/weapons/gmod_tool/stools/ragmover_ikchains.lua
lua/weapons/gmod_tool/stools/ragmover_propragdoll.lua
resource/localization/en/ragdollmover_tools.properties

Added experimental new tool - Prop ragdoll, which allows to trick ragdoll mover into treating set of connected props as a single ragdoll along with all functions ragdoll mover provides, IKs included!
Reworked ragdoll mover and IK chains tool to work with these prop ragdolls
Optimized net messages a bit
Made it so getting updates for bone manipulation sliders would not trigger their net messages to the server
Ragdoll mover's constrained entities tab will now ignore parented entities
Ragdoll mover's IK Chain tool can save IKs for prop ragdolls
Removed check in ragdoll mover that was meant to prevent gmod crashes from INF and NaN decimals which I did to fix prop ragdolls sometimes not moving some props at all. I didn't crash my gmod yet, although that would needed to be checked out some more …

Prop ragdoll tool

---

lua/autorun/ragdollmover.lua
lua/entities/rgm_axis/init.lua
lua/entities/rgm_axis_arrow/init.lua
lua/entities/rgm_axis_disc/init.lua
lua/entities/rgm_axis_scale_arrow/init.lua
lua/entities/rgm_axis_scale_side/init.lua
lua/entities/rgm_axis_side/init.lua
lua/entities/rgm_axis_side_omni/init.lua
lua/weapons/gmod_tool/stools/ragdollmover.lua
resource/localization/en/ragdollmover_tools.properties
resource/localization/ru/ragdollmover_tools.properties

- Fixed IK rigs error when moving physical bones through nonphysical ones
- Further fix to unexpected movement when grabbing arrows that point upwards
- Changed amount of bones to look through for phys parent lookup function to 256 from 512 (apparently SFM doesn't support over 256 bones either, after consulting the VDC, also I didn't alter UInt net message amount of bits to 9 from 10 to account for that)
- Physbone movement done through nonphysics manipulation tab now is added to Physgun Undo
- Reset all bones in precise nonphysics bone manipulation tab will now actually reset all bones
- Select All in IKs tab now switches its texts depending on whether it'll select all IKs or deselect them
- Added some calculation exceptions for Advanced Bonemerge entities due to them using overriden …

Fixes + Advanced Bonemerge compatibility

---

lua/autorun/ragdollmover.lua
lua/entities/rgm_axis/cl_init.lua
lua/entities/rgm_axis/init.lua
lua/ragdollmover/rgm_gizmos.lua
lua/weapons/gmod_tool/stools/ragdollmover.lua
resource/localization/en/ragdollmover_tools.properties
resource/localization/ru/ragdollmover_tools.properties

- Fixed lua error in a specific case with scaling bones
- Removed slider clamping in gizmo offsets
- Rearranged toolmenu
- Relative scaling root bone on effect props now works properly
- Relative scaling now only scales each bone by 1 axis which is the most aligned with the scale vector
- Tool can now manipulate objects from camera entity view, although it may not work properly with offset feature in advanced cameras

Adjustments

---

lua/autorun/ragdollmover.lua
lua/entities/rgm_axis/cl_init.lua
lua/ragdollmover/constants.lua
lua/weapons/gmod_tool/stools/ragdollmover.lua
lua/weapons/gmod_tool/stools/ragmover_propragdoll.lua

- Radial adv bone select now spaces out bones a bit more so it is easier to see them when there's more of them selected, although it gets messy with a lot of bones selected, however that should not be the case in general use
- Locking bone scale should now not prevent movement of bones when using relative scale
- Made adv bone select UI scale with screen resolution, added custom fonts that scale to the screen res on game start
- Fixed error related to pressing any button when dead in multiplayer

UI Scaling to screen res

---

lua/autorun/ragdollmover.lua
lua/autorun/ragdollmover_meta.lua
lua/ragdollmover/constants.lua
lua/ragdollmover/rgm_gizmos.lua
lua/weapons/gmod_tool/stools/ragdollmover.lua
lua/weapons/gmod_tool/stools/ragmover_ikchains.lua

- Relative bone scale now has more precise scaling
Unrelated:
- UI now shows bones in different colors, green - physical, cyan - nonphys, yellow - procedural and red for parented
- Fixed some errors related to Adv Bone select
- Added lua file that contains all constants for ragdoll mover like vectors and colors for easier editing them everywhere
- Fixed rgm entity spawning without its convars being set
- Bone scaling functions were moved into a single function
- Fixed setting gizmo offset to bones on nonphys entities
- Some performance improvements
- Moving stuff through camera with RGM now works with advanced camera offset
- Added ragdollmover_always_use_pl_view convar to always use player view when moving stuff, and holding down gizmo will use the view of whatever entity you were using …

Relative Scale Adjustment

---

lua/entities/rgm_axis/init.lua
lua/entities/rgm_axis/shared.lua

- We set their collision bounds to contain the player; if the player is in the world, the gizmo will update its position, even if it is out of bounds. This allows the user to still move the gizmo around when it is out of bounds (e.g. using IK chains for foot placement, or for props with visually inconsistent origins)

Make the gizmo update its position when out of bounds

---

lua/autorun/ragdollmover.lua
lua/ragdollmover/rgm_gizmos.lua
lua/weapons/gmod_tool/stools/ragdollmover.lua

Put net messages in Ragdoll Mover tool into a table which should make navigating it easier for future contributors.
Did some clean up in the code.
Fixed some physical bone position errors when using middle mouse on sliders in Precise Nonphysical Bone manipulation with "Move physical bones with nonphysical" option on.
Gray rotation gizmo now can not rotate nonphysical bones.

Readability

---

lua/autorun/ragdollmover_meta.lua
lua/entities/rgm_axis/shared.lua
lua/weapons/gmod_tool/stools/ragdollmover.lua

* Fix gizmos not catching up to cursor position
+ By default, the rgm_axis is created with MOVETYPE_NONE on the client, which causes the gizmo to delay its movement to the cursor. This fixes it by setting its movetype to MOVETYPE_VPHYSICS, replicating the behavior seen from tool ghost entities.
* Fixed inability to click on gizmos in some environments
* Change behavior for func_brush functionality
+ Added InitPostEntity hook to insert ragdollmover to all func_brush entities with a m_tblToolsAllowed field, which fixes unselectable gizmos in func_brush entities for singleplayer and multiplayer
- Removed rgm_ghost and ghost padding implementations, which has been superseded by the above hook
* Generalize to entities with brush planes instead of strictly func_brush
* Improved appending of …

Additional gizmo enhancements (#13)

---

lua/autorun/ragdollmover.lua
lua/weapons/gmod_tool/stools/ragdollmover.lua

* Use `util.IsPointInCone` instead of `pos.visible` to restrict edge cases
* Further restrict the view cone angle
* Cache util.IsPointInCone in prevbones[i]; if it exists, we calculate fraction and color
- Also use cached result so we do not have to get bone positions
* Initially set `BoneColors = {}`, so we don't need to do `prevbones = {}` on `calc`
* View entity support for AdvBoneSelectRender
* Opt to use the forward vector of the view entity, instead of cursor vector

Use `util.IsPointInCone` instead of `pos.visible` (#14)

---

lua/entities/rgm_axis/cl_init.lua
lua/entities/rgm_axis/shared.lua
lua/ragdollmover/rgm_gizmos.lua
lua/weapons/gmod_tool/stools/ragdollmover.lua

- Adds a ball gizmo to the rotation mode, which allows physical bones or parented bones (such as the root bone of an effect prop's entity) to be rotated in any arbitrary direction. Resolves #21
- Hides the ball and large, gray disc gizmo when accessing nonphysical bones, as these bones are more likely to gimbal lock from rotation at any axis. (Rotating a nonphysical bone from any arbitrary axis is an open problem that any can attempt to solve).

Spherical Rotation

---

lua/weapons/gmod_tool/stools/ragdollmover.lua

Angle snapping and "Move physbones with nonphysbones" settings were moved under bone manipulation tab rather than misc one, and activating angle snapping will now show slider for setting angle snap angles, which is now hidden by default.
Convar for enabling spherical rotation gizmo is now disabled by default when first installing the update (ragdollmover_drawsphere). Shouldn't affect those who already had the version with spherical gizmo and had it enabled

UI Adjustments

---

lua/autorun/ragdollmover.lua
lua/entities/rgm_axis/cl_init.lua
lua/entities/rgm_axis/init.lua
lua/entities/rgm_axis/shared.lua
lua/ragdollmover/rgm_gizmos.lua
lua/weapons/gmod_tool/stools/ragdollmover.lua

- More optimizations.
- Grabbing onto scaling gizmo will now also show numbers for the current scale on related axises.
- Fixed relative bone scaling not working on physprops with 1 bone.
- Gizmo parts that face the player will now keep their rotation when they are being held - should prevent weird movements when switching view to a camera or back.

Scale Text

---

lua/autorun/ragdollmover.lua
lua/weapons/gmod_tool/stools/ragdollmover.lua

- Fixed gizmo mismatch on advanced bonemerge entities.
- Fixed selecting nonphysical entities (like bonemerged entities) not properly selecting their root bone.
- Fixed error related when looking through old advanced cameras that did not have view offset.

Advanced Bonemerge + Old Advanced Cameras fix

---

lua/autorun/ragdollmover.lua
lua/weapons/gmod_tool/stools/ragdollmover.lua
resource/localization/en/ragdollmover_tools.properties

- Changed behavior of saving lock data and constrained entity data when switching between entities; instead of resetting locks automatically when switching entities, they stay preserved
- Added manual lock resetting concommands `ragdollmover_resetlocks` and `ragdollmover_resetalllocks`; the former concommand resets locks for the player's selected entity, while the latter resets locks for all entities that the player has added locks to in the past
- Added duplicator and GMod save support for lock data and constrained entity data. Locks such as position, angle, scale, and bones can be duplicated or saved. Constrained entity data (locks between one entity to another entity) can also be duplicated or saved
- Changed entity lock data structure to be keyed per entity, which stores its locked …

Save lock data and constrained entity data

---

lua/autorun/client/ragdollmover_client.lua
lua/autorun/ragdollmover.lua
lua/autorun/ragdollmover_meta.lua
lua/weapons/gmod_tool/stools/ragdollmover.lua
lua/weapons/gmod_tool/stools/ragmover_ikchains.lua
lua/weapons/gmod_tool/stools/ragmover_propragdoll.lua

- Fixed error related to relying on InitPostEntity hook for initializing variables.
- Added entity and bone locking support to Prop Ragdolls.
- Various optimizations and fixes for bone locks.
- IK data from IK chains tool now gets saved into entities for duping.
- Fixed Prop Ragdoll data not being saved in a dupe if original Prop Ragdoll was deleted during game session.

InitPostEntity bugfix and further locking improvements
